/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
#include "stm32l476xx.h"
#include "gpio_driver.h"

int main(void)
{
    // 1) Switch system clock to HSI16
    SystemClock_HSI16();

    // 2) Enable ports and configure pins
    gpio_enable_port_clock(GPIOA);
    gpio_enable_port_clock(GPIOC);

    // PA5: output (LD2)
    gpio_config_pin(GPIOA, 5, GPIO_MODE_OUTPUT, GPIO_PULL_NONE);
    // PC13: input (User button on many Nucleo boards) with pull-up
    gpio_config_pin(GPIOC, 13, GPIO_MODE_INPUT, GPIO_PULL_UP);

    // Loop: toggle LED every ~200ms, but if button pressed (active low on many boards), keep LED on
    while (1)
    {
        uint8_t btn = gpio_read_pin(GPIOC, 13); // 1 when not pressed if pull-up
        if (btn == 0) {
            // button pressed (active low) -> LED ON
            gpio_write_pin(GPIOA, 5, 1);
            // short debounce delay
            for (volatile int d=0; d<200000; d++);
        } else {
            // blink
            gpio_toggle_pin(GPIOA, 5);
            for (volatile int d=0; d<200000; d++);
        }
    }
    // never reached
    return 0;}
