/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
#include "stm32l476xx.h"
#include "gpio_driver.h"
#include "exti_gpio.h"


// IRQ Handler for EXTI lines 10..15
void EXTI15_10_IRQHandler(void)
{
// Check pending for line 13
if (EXTI->PR1 & (1U << 13)) {
// Clear pending
EXTI->PR1 = (1U << 13);
// Simple debounce: small delay (avoid long operations in IRQ in real apps)
for (volatile int i=0; i<200000; i++);
// Toggle LED (PA5)
GPIOA->ODR ^= (1U << 5);
}
}


int main(void)
{
// Switch to HSI16
SystemClock_HSI16();


// Enable GPIO clocks
gpio_enable_port_clock(GPIOA);
gpio_enable_port_clock(GPIOC);


// Configure PA5 as output (LD2)
gpio_config_pin(GPIOA, 5, GPIO_MODE_OUTPUT, GPIO_PULL_NONE);


// Configure PC13 as input with pull-up
gpio_config_pin(GPIOC, 13, GPIO_MODE_INPUT, GPIO_PULL_UP);


// Configure EXTI for PC13 (pin 13) falling edge
exti_configure_pin(GPIOC, 13, 1, 0);


// NVIC: set priority and enable EXTI15_10
NVIC_SetPriority(EXTI15_10_IRQn, 2);
NVIC_EnableIRQ(EXTI15_10_IRQn);


// wait for interrupts
while (1) {
__WFI();
}


return 0;
}
